# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/SIDNEY/Documents/Xilinx/DVI_HDMI/DVI_HDMI/DVI_HDMI.srcs/sources_1/bd/DVI/ip/DVI_clk_wiz_0_5/DVI_clk_wiz_0_5.xci
# IP: The module: 'DVI_clk_wiz_0_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/SIDNEY/Documents/Xilinx/DVI_HDMI/DVI_HDMI/DVI_HDMI.srcs/sources_1/bd/DVI/ip/DVI_clk_wiz_0_5/DVI_clk_wiz_0_5_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'DVI_clk_wiz_0_5'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/SIDNEY/Documents/Xilinx/DVI_HDMI/DVI_HDMI/DVI_HDMI.srcs/sources_1/bd/DVI/ip/DVI_clk_wiz_0_5/DVI_clk_wiz_0_5.xdc
# XDC: The top module name and the constraint reference have the same name: 'DVI_clk_wiz_0_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/SIDNEY/Documents/Xilinx/DVI_HDMI/DVI_HDMI/DVI_HDMI.srcs/sources_1/bd/DVI/ip/DVI_clk_wiz_0_5/DVI_clk_wiz_0_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DVI_clk_wiz_0_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/SIDNEY/Documents/Xilinx/DVI_HDMI/DVI_HDMI/DVI_HDMI.srcs/sources_1/bd/DVI/ip/DVI_clk_wiz_0_5/DVI_clk_wiz_0_5.xci
# IP: The module: 'DVI_clk_wiz_0_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/SIDNEY/Documents/Xilinx/DVI_HDMI/DVI_HDMI/DVI_HDMI.srcs/sources_1/bd/DVI/ip/DVI_clk_wiz_0_5/DVI_clk_wiz_0_5_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'DVI_clk_wiz_0_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/SIDNEY/Documents/Xilinx/DVI_HDMI/DVI_HDMI/DVI_HDMI.srcs/sources_1/bd/DVI/ip/DVI_clk_wiz_0_5/DVI_clk_wiz_0_5.xdc
# XDC: The top module name and the constraint reference have the same name: 'DVI_clk_wiz_0_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/SIDNEY/Documents/Xilinx/DVI_HDMI/DVI_HDMI/DVI_HDMI.srcs/sources_1/bd/DVI/ip/DVI_clk_wiz_0_5/DVI_clk_wiz_0_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DVI_clk_wiz_0_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
