# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/DVI.xdc

# Block Designs: bd/DVI/DVI.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DVI || ORIG_REF_NAME==DVI} -quiet] -quiet

# IP: bd/DVI/ip/DVI_input_block_0_0/DVI_input_block_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DVI_input_block_0_0 || ORIG_REF_NAME==DVI_input_block_0_0} -quiet] -quiet

# IP: bd/DVI/ip/DVI_TMDS_encoder_V2_0_0/DVI_TMDS_encoder_V2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DVI_TMDS_encoder_V2_0_0 || ORIG_REF_NAME==DVI_TMDS_encoder_V2_0_0} -quiet] -quiet

# IP: bd/DVI/ip/DVI_TMDS_encoder_V2_1_0/DVI_TMDS_encoder_V2_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DVI_TMDS_encoder_V2_1_0 || ORIG_REF_NAME==DVI_TMDS_encoder_V2_1_0} -quiet] -quiet

# IP: bd/DVI/ip/DVI_TMDS_encoder_V2_2_0/DVI_TMDS_encoder_V2_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DVI_TMDS_encoder_V2_2_0 || ORIG_REF_NAME==DVI_TMDS_encoder_V2_2_0} -quiet] -quiet

# IP: bd/DVI/ip/DVI_xlconstant_0_0/DVI_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DVI_xlconstant_0_0 || ORIG_REF_NAME==DVI_xlconstant_0_0} -quiet] -quiet

# IP: bd/DVI/ip/DVI_xlconstant_1_0/DVI_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DVI_xlconstant_1_0 || ORIG_REF_NAME==DVI_xlconstant_1_0} -quiet] -quiet

# IP: bd/DVI/ip/DVI_util_vector_logic_0_0/DVI_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DVI_util_vector_logic_0_0 || ORIG_REF_NAME==DVI_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/DVI/ip/DVI_selectio_wiz_0_2/DVI_selectio_wiz_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DVI_selectio_wiz_0_2 || ORIG_REF_NAME==DVI_selectio_wiz_0_2} -quiet] -quiet

# IP: bd/DVI/ip/DVI_selectio_wiz_0_3/DVI_selectio_wiz_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DVI_selectio_wiz_0_3 || ORIG_REF_NAME==DVI_selectio_wiz_0_3} -quiet] -quiet

# IP: bd/DVI/ip/DVI_selectio_wiz_0_4/DVI_selectio_wiz_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DVI_selectio_wiz_0_4 || ORIG_REF_NAME==DVI_selectio_wiz_0_4} -quiet] -quiet

# IP: bd/DVI/ip/DVI_processing_system7_0_0/DVI_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DVI_processing_system7_0_0 || ORIG_REF_NAME==DVI_processing_system7_0_0} -quiet] -quiet

# IP: bd/DVI/ip/DVI_M_AXI_Lite_READ_0_3/DVI_M_AXI_Lite_READ_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DVI_M_AXI_Lite_READ_0_3 || ORIG_REF_NAME==DVI_M_AXI_Lite_READ_0_3} -quiet] -quiet

# IP: bd/DVI/ip/DVI_blk_mem_gen_0_0/DVI_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DVI_blk_mem_gen_0_0 || ORIG_REF_NAME==DVI_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/DVI/ip/DVI_BLK_MEM_addres_gen_0_0/DVI_BLK_MEM_addres_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DVI_BLK_MEM_addres_gen_0_0 || ORIG_REF_NAME==DVI_BLK_MEM_addres_gen_0_0} -quiet] -quiet

# IP: bd/DVI/ip/DVI_line_addr_gen_0_0/DVI_line_addr_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DVI_line_addr_gen_0_0 || ORIG_REF_NAME==DVI_line_addr_gen_0_0} -quiet] -quiet

# IP: bd/DVI/ip/DVI_axi_mem_intercon_7/DVI_axi_mem_intercon_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DVI_axi_mem_intercon_7 || ORIG_REF_NAME==DVI_axi_mem_intercon_7} -quiet] -quiet

# IP: bd/DVI/ip/DVI_res_select_0_0/DVI_res_select_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DVI_res_select_0_0 || ORIG_REF_NAME==DVI_res_select_0_0} -quiet] -quiet

# IP: bd/DVI/ip/DVI_rst_ps7_0_100M_0/DVI_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DVI_rst_ps7_0_100M_0 || ORIG_REF_NAME==DVI_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/DVI/ip/DVI_clk_wiz_0_5/DVI_clk_wiz_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DVI_clk_wiz_0_5 || ORIG_REF_NAME==DVI_clk_wiz_0_5} -quiet] -quiet

# IP: bd/DVI/ip/DVI_auto_pc_0/DVI_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DVI_auto_pc_0 || ORIG_REF_NAME==DVI_auto_pc_0} -quiet] -quiet

# XDC: bd/DVI/DVI_ooc.xdc
