# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/SIDNEY/Documents/Xilinx/DVI_HDMI/DVI_HDMI/DVI_HDMI.srcs/sources_1/bd/DVI/ip/DVI_processing_system7_0_0/DVI_processing_system7_0_0.xci
# IP: The module: 'DVI_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/SIDNEY/Documents/Xilinx/DVI_HDMI/DVI_HDMI/DVI_HDMI.srcs/sources_1/bd/DVI/ip/DVI_processing_system7_0_0/DVI_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'DVI_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/SIDNEY/Documents/Xilinx/DVI_HDMI/DVI_HDMI/DVI_HDMI.srcs/sources_1/bd/DVI/ip/DVI_processing_system7_0_0/DVI_processing_system7_0_0.xci
# IP: The module: 'DVI_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/SIDNEY/Documents/Xilinx/DVI_HDMI/DVI_HDMI/DVI_HDMI.srcs/sources_1/bd/DVI/ip/DVI_processing_system7_0_0/DVI_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'DVI_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
