@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Nov 08 15:28:25 +0530 2019
REM SW Build 2700185 on Thu Oct 24 18:46:05 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim DVI_wrapper_func_synth -key {Post-Synthesis:sim_1:Functional:DVI_wrapper} -tclbatch DVI_wrapper.tcl -protoinst "protoinst_files/DVI.protoinst" -log simulate.log"
call xsim  DVI_wrapper_func_synth -key {Post-Synthesis:sim_1:Functional:DVI_wrapper} -tclbatch DVI_wrapper.tcl -protoinst "protoinst_files/DVI.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
